apiVersion: v1
kind: Service
metadata:
  name: fastapi-graceful
  namespace: kkamji
spec:
  type: NodePort
  selector:
    app: fastapi-graceful
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30036
